version: '3'

services:
  db:
    image: postgres
    container_name: u4i-db
    env_file:
      - ./db/.env.db
    volumes:
      - ./db/data/:/var/lib/postgresql/data/
    ports:
      - '5432:5432'

  php-fpm:
    build: ./php-fpm
    container_name: u4i-php
    working_dir: /code
    volumes:
      - ../application:/code
      - ./php-fpm/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    ports:
      - '9000:9000'

  nginx:
    image: nginx:latest
    container_name: u4i-nginx
    ports:
      - "80:80"
    working_dir: /code
    volumes:
      - ../application:/code
      - ./nginx/config/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/config/proxy_params:/etc/nginx/proxy_params
      - ./nginx/config/fastcgi.conf:/etc/nginx/fastcgi.conf
